---
title: "Papers"
---
*Last update: 2026/01/11*

## Published papers

- *[Inflation Shock and Monetary Policy](https://link.springer.com/chapter/10.1007/978-3-031-61561-0_4)* In: Mátyás, L. (eds) Central and Eastern European Economies and the War in Ukraine. Contributions to Economics. Springer, Cham. https://doi.org/10.1007/978-3-031-61561-0_4 
  - Joint work with Szilárd Benk and Norbert Szepesi
  - **Abstract:** The war in Ukraine triggered the most substantial surge in inflation rates in decades, posing a formidable challenge for the central banks of Central and Eastern Europe (CEE) to curb inflation without compromising the ongoing post-Covid recovery. This chapter provides a brief discussion of the factors contributing to the inflationary pressure and evaluates the monetary policy responses in the region. The root cause of the inflationary pressure lies primarily in supply-side shocks disrupting international trade channels as a consequence of the war. Countries with loose monetary conditions witnessed the most pronounced spike in inflation rates in the aftermath of the war. Despite these challenges, central banks responded promptly, implementing aggressive interest rate hikes, keeping monetary conditions tight throughout 2022 and well after inflation rates began to decrease in 2023.

- *[Nonlinear Transmission of Monetary Policy and Housing Market Imbalances: Evidence From a Factor-Augmented Threshold VAR Analysis](https://doi.org/10.1111/manc.70034)*
  - **Abstract:** In recent decades, persistently low rates have driven housing booms and prompted questions on how market imbalances interact with monetary policy. In this paper, I investigate how such imbalances affect the monetary transmission in the United States. I create a boom-bust cycle indicator from the rent‑price ratio and credit‑to‑GDP gap, then embed it in a factor‑augmented threshold VAR with two regimes to isolate the two parts of the cycle. Impulse responses show that monetary policy itself behaves differently conditional on the state of the housing market. Interest rates are eased much more gradually around booms, which suggests that broader macro-financial signals are incorporated into the policy framework in order to effectively manage deleveraging in the market. The transmission channel appears to be less affected, as real and financial aggregates show only somewhat larger contractions in response to a monetary policy shock in a booming market.

## Dissertation chapters

- **Chapter 1:** *[Monetary Transmission in a fragmented uncertain world](papers/uncertainty_transmission.pdf)* 
  - Joint work with Tohid Atashbar (IMF) during the Fund Internship Program.
  - **Abstract:** In this paper, we investigate the nonlinear relationship between economic uncertainty and the monetary transmission mechanism. We use a Threshold Vector Autoregression model and impose sign-restrictions on quarterly interest rates, GDP growth, and CPI inflation across a broad range of countries. Our findings suggest that during periods of elevated uncertainty, monetary shocks lead to more profound economic contractions, followed by sluggish output adjustments. The effectiveness in curbing inflation exhibits mixed results contingent on the underlying uncertainty narrative. Nonetheless, the overarching trend in our results tends to support the notion that heightened uncertainty acts as a channel for propagating shocks, thereby amplifying their influence. Consequently, our implications for policymakers emphasize that while heightened uncertainty does not inherently hinder the transmission mechanism, it does disrupt monetary policy by escalating the costs associated with reducing inflation.
  - **Stage:** Conference-ready (Please click the link above to read the latest version of the working paper.)
  
\vspace{4em}


- **Chapter 2:** *[Nonlinear Transmission of Monetary Policy and Housing Market Imbalances: Evidence from a Factor-Augmented Threshold VAR Analysis?](papers/housing_tfavar.pdf)*
  - **Stage:** Published, please see above.

\vspace{4em}
  
- **Chapter 3:** *[A Distributional Perspective on Forward Guidance and the US Term Structure](papers/forwardguidance_volatility.pdf)* 
  - **Abstract:** This paper revisits the impact of forward guidance on the term structure of U.S. interest rates. Using a dynamic location–scale model, I find that FOMC forward guidance announcements not only depress the yield curve, but also reduce the conditional volatility of yield changes. The volatility channel is persistent across maturities and strongest at shorter ones. This volatility effect is consistent across nominal and real yields, as well as implied expected inflation. These results are robust to a number of specification, including ones that account for central bank information shocks and ones that exclude forward guidance conducted when rates were near the zero lower bound.
  - **Stage:** Conference-ready (Please click the link above to read the latest version of the working paper.)


## Ongoing research projects

- *[How does grant design shape investment, output, and productivity in Europe?](papers/macrogrants.pdf)* 
  - Joint work with Atanas Kolev (EIB) and Laurent Maurin (EIB) during the EIB Traineeship Program.
  - **Abstract:** This paper investigates the impact of government investment grants on investments, output and productivity across EU economies. We estimate Bayesian Vector Autoregressions for a wide range of EU countries using priors derived at the EU level. We then use a mix of impact restrictions as well as short-run and long-run sign restrictions to identify two types of grant allotments: demand-support and productivity-enhancing. We find that, compared to demand-support grants, productivity-enhancing grants translate into much larger gains in investment and output as well. We also find that the permanent increase in productivity is due to the fact that such grants are allocated to more productive investments, such as intellectual property products. In contrast, demand-support grants are more likely to be allocated to replenishing physical capital, as shown by the response of investment in machinery and equipment. The magnitude of the responses appears to vary substantially across European economies in our sample. We use the EIB Investment Survey to better understand these differences. We match the estimated responses with survey information to characterize the investment environment in each country. We find characteristics, such as the prevailing uncertainty, the cost of bureaucracy, or the degree of fragmentation, do explain part of the differences in the macroeconomic response. Overall, our analysis emphasizes that the nature of grants and the rationale behind their allotment influence the macroeconomic benefits. Moreover, providing a business environment more suitable to investment also raises the impact of the public financial support to corporate investment.
  - **Stage:** Conference-ready (Please click the link above to read the latest version of the working paper.)

\vspace{8em}

Please feel free to reach out for replication files, or check my GitHub repos [here](https://github.com/peterhorvath97?tab=repositories).

[back](./)